services:
  postgres:
    image: postgres:16
    restart: always
    tty: true
    stdin_open: true
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    restart: always
    tty: true
    stdin_open: true
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./tmp/minio/data:/data:z
    ports:
      - "9092:9000"
      - "9093:9001"
    command: server /data --console-address ":9001"